version: '3.8'

services:
  postgres:
    image: postgres
    container_name: test_postgres_container
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
