version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: my_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
