version: '3.8'

services:
  postgres:
    image: postgres
    container_name: test_postgres_container
    ports:
      - '${DB_PORT}:5432'
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres-data:
  redis_data:
